[images]
  remote_images = ["https://picsum.photos/.*", "https://fastly.picsum.photos/.*", "https://images.unsplash.com/.*", "https://source.unsplash.com/.*", "https://github.com/.*"]
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
