title: Movement Prep
description: Activation and warm-up movements designed to prepare the body for training by improving mobility, muscle activation, and movement patterns.
slug: movement-prep
parent: true
