title: Cleans
description: Technical movements that bring the kettlebell from a lower position to rack position, developing power, coordination, and movement skill.
slug: kettlebell-cleans
parent: true
