title: Rowing/Pulling Movements
description: Exercises that pull kettlebells toward the body, strengthening the back, rear delts, and biceps while improving posture and posterior strength.
id: rowing-pulling
parent: true
