title: Curls & Extensions
description: Isolation exercises that target specific muscle groups, primarily the biceps and triceps, to complement compound movements with focused muscle development.
slug: curls-extensions
parent: true
