title: Carries/Holds
description: Static and walking exercises that build grip strength, core stability, and muscular endurance by maintaining kettlebell positions for extended periods.
id: carries-holds
parent: true
