title: Single Leg/Balance Movements
description: Unilateral exercises performed on one leg that challenge balance, proprioception, and single-limb strength while addressing muscular imbalances.
slug: single-leg-balance
parent: true
